# ============================================================================
# FARE REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-10-23 11:26:56 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.fare import FareUpdate, FareCreate, FareOut

async def create_fare(fare_data: FareCreate) -> FareOut:
    fare_dict = fare_data.model_dump()
    result =await db.fares.insert_one(fare_dict)
    result = await db.fares.find_one(filter={"_id":result.inserted_id})
    returnable_result = FareOut(**result)
    return returnable_result

async def get_fare(filter_dict: dict) -> Optional[FareOut]:
    try:
        result = await db.fares.find_one(filter_dict)

        if result is None:
            return None

        return FareOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching fare: {str(e)}"
        )
    
async def get_fares(filter_dict: dict = {},start=0,stop=100) -> List[FareOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.fares.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        fare_list = []

        async for doc in cursor:
            fare_list.append(FareOut(**doc))

        return fare_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching fares: {str(e)}"
        )
async def update_fare(filter_dict: dict, fare_data: FareUpdate) -> FareOut:
    result = await db.fares.find_one_and_update(
        filter_dict,
        {"$set": fare_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = FareOut(**result)
    return returnable_result

async def delete_fare(filter_dict: dict):
    return await db.fares.delete_one(filter_dict)